flowchart LR
    subgraph 
        A["User Verification"] --> B["Name"]
        A --> C["Email"]
        A --> D["Password"]
    end

    subgraph 
        E["Details"] --> F["Name"]
        E --> G["Description"]
        E --> H["Status"]
        E --> I["File"]
        E --> J["Created by"]
        E --> K["Created at"]
        E --> L["Deleted at"]
        E --> M["Completed at"]
        E --> N["Updated at"]
    end

    subgraph 
        O["Assignment Table"] --> P["Assigned to"]
        O --> Q["Assigned at"]
    end
