%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#ffffff', 'edgeLabelBackground': '#ffffff', 'lineColor': '#ffffff'}}}%%
flowchart TD
    A["users"] -->|id| A1["name"]
    A --> A2["password"]
    A --> A3["email"]
    
    B["tickets"] -->|id| B1["name"]
    B --> B2["description"]
    B --> B3["status"]
    B --> B4["created_by"]
    B --> B5["created_at"]
    B --> B6["updated_at"]
    B --> B7["completed_at"]
    B --> B8["deleted_at"]
    
    C["assignments"] -->|id| C1["ticket_id"]
    C --> C2["assigned_to"]
    C --> C3["assigned_at"]
